//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CantidadPremiosPorCompetidor
    {
        public int Id { get; set; }
        public Nullable<int> CantidadPremios { get; set; }
        public Nullable<int> Año { get; set; }
        public Nullable<int> idCompetidor { get; set; }
    
        public virtual Competidor Competidor { get; set; }
    }
}
